# The name of the workflow
name: Test

# This workflow will run on any push to the repository
on: push

jobs:
  test:
    # Similar to docker, we set up a virtual machine to run our tests
    runs-on: ubuntu-latest

    steps:
      # Each step has a name, some code, and some options
      - name: Check out the code
        uses: actions/checkout@v3 # This is a reference to some code to run

      # This step installs the Node version
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      # This step installs dependencies
      - name: Install dependencies
        run: npm install
      
      # Test React app
      - name: Test
        run: npm run test
